### ISSUE TITLE
ENGINE Error in HTTPServer.tick Traceback with SABnzbd 3.0

### ISSUE THREAD

**Issue by StevenNexus** [sabnzbd/sabnzbd#1577]
I started getting this new error right after upgrading to sabnzbd 3.0. Any suggestion how to fix? Does not seem to be fatal error as I can still access the webGUI via https.

OS = Ubuntu 18.04.5 LTS
Python-version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
SSL version = OpenSSL 1.1.1  11 Sep 2018

Error message from log:
```
2020-08-16 02:17:48,196::INFO::[__init__:350] All processes started
2020-08-16 02:17:48,196::INFO::[sabnzbdplus:292] Template location for Glitter is /usr/share/sabnzbdplus/interfaces/Glitter
2020-08-16 02:17:48,196::INFO::[sabnzbdplus:292] Template location for Config is /usr/share/sabnzbdplus/interfaces/Config
2020-08-16 02:17:48,204::INFO::[sabnzbdplus:393] SABYenc module (v4.0.1)... found!
2020-08-16 02:17:48,205::INFO::[sabnzbdplus:412] Cryptography module (v2.1.4)... found!
2020-08-16 02:17:48,205::INFO::[sabnzbdplus:417] par2 binary... found (/usr/bin/par2)
2020-08-16 02:17:48,205::INFO::[sabnzbdplus:424] UNRAR binary... found (/usr/bin/unrar)
2020-08-16 02:17:48,205::INFO::[sabnzbdplus:432] UNRAR binary version 5.50
2020-08-16 02:17:48,205::INFO::[sabnzbdplus:440] 7za binary... found (/usr/bin/7za)
2020-08-16 02:17:48,205::INFO::[sabnzbdplus:451] nice binary... found (/usr/bin/nice)
2020-08-16 02:17:48,206::INFO::[sabnzbdplus:455] ionice binary... found (/usr/bin/ionice)
2020-08-16 02:17:48,206::INFO::[sabnzbdplus:1276] HTTPS keys are OK
2020-08-16 02:17:48,207::INFO::[sabnzbdplus:1403] Starting web-interface on xxx:8080
2020-08-16 02:17:48,208::INFO::[_cplogging:219] [16/Aug/2020:02:17:48] ENGINE Bus STARTING
2020-08-16 02:17:48,209::INFO::[_cplogging:219] [16/Aug/2020:02:17:48] ENGINE Started monitor thread '_TimeoutMonitor'.
2020-08-16 02:17:48,339::INFO::[_cplogging:219] [16/Aug/2020:02:17:48] ENGINE Serving on https://xxx:8080
2020-08-16 02:17:48,340::INFO::[_cplogging:219] [16/Aug/2020:02:17:48] ENGINE Bus STARTED
2020-08-16 02:17:48,340::INFO::[sabnzbdplus:1440] Starting sabnzbdplus-3.0.0
2020-08-16 02:17:48,340::DEBUG::[__init__:361] Starting postprocessor
2020-08-16 02:17:48,342::ERROR::[_cplogging:219] [16/Aug/2020:02:17:48] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

**Comment by Safihre** [comment]
https://github.com/sabnzbd/sabnzbd/issues/1576#issuecomment-674414212
Bug in Python core.

**Comment by StevenNexus** [comment]
Thanks, closing issue.

**Comment by Safihre** [comment]
Actually, in your case it seems this should be fixed by updating `cherrypy` and `cheroot`.
The new versions of these include a workaround for the bug. 
https://github.com/cherrypy/cheroot/blob/master/cheroot/ssl/builtin.py#L324

How do you run sabnzbd? So we can give you instructions how to update.

**Comment by StevenNexus** [comment]
I run direct on Ubuntu using JCFP's PPA. Not sure if this is all you need to know or not.

**Comment by Safihre** [comment]
Aaah.
@jcfp Is there a way to include a more recent version of `cherrypy`/`cheroot` in the PPA?
It was patched in `cheroot==6.5.3` about 2 years ago: https://github.com/cherrypy/cheroot/commit/42bc79d860e0c8423de98fffad9bf1a65a4b35aa

**Comment by jcfp** [comment]
The cheroot package in debian is at some recent version, the problem is cherrypy which is old enough to not even need cheroot...  Including it in the ppa is possible but risky; the official repos still have some ancient 2017 version of cherrypy (iirc because of some compatibility issues - don't know if that's still a problem). Meaning a full-blown update of that cherrypy package is needed rather than just a plain backport and I could still end up breaking unrelated stuff even if I get everything right.

I'll ask around to see if updating the official cherrypy is an option. No ETA though.

**Comment by gussyboy** [comment]
Hey, late the party, I've just updated my docker version to 3.0.0 and getting the same issue. I've using https://github.com/linuxserver/docker-sabnzbd image. Hows the best way to resolve this error?

**Comment by Safihre** [comment]
The Docker uses the PPA, so it's to be expected. They could change that, I'll create an issue for that.

**Comment by OneCDOnly** [comment]
@Safihre can you please advise if the issue discussed here is the same as the one I'm seeing in when enabling SSL in SABbznd?  https://github.com/OneCDOnly/sherpa/issues/83

Only happens on the first SSL access to SAB. Subsequent access is fine. 😕

**Comment by sanderjo** [comment]
Little summary how I understand it (corrections welcome)

It happens on Ubuntu, with HTTPS access to SABnzbd turned on.

Causes:
- Ubuntu has an old version of cherrypy. The bug was already solved in cherrypy / cheroot in 2018 or so, but Ubuntu is on the 2017 version.
- The underlying problem is a bug in Python itself, which was solved in August 2020, and which will probably takes months or longer to arrive in a python release on Linux.

Most easy: You can ignore the Traceback. It happens once at startup of SABnzbd, and does no harm.

A workaround for this is to not install the cherrypy and any other sabnzbdplus dependencies from Ubuntu, but from pip (which are uptodate). Warning: you can run into jaraco problems (https://github.com/sabnzbd/sabnzbd/issues/1522, https://github.com/sabnzbd/sabnzbd/issues/1546) if you don't do it correctly, read: have a mix of python libraries.

**Comment by iio7** [comment]
I'm running SABnzbd on Arch Linux with the latest of everything, also getting the bug. In my case downloading isn't working as long as this bug is present.

```
ERROR 2 minutes ago [19/Aug/2020:13:22:04] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cheroot/server.py", line 1795, in serve
    self.tick()
  File "/usr/lib/python3.8/site-packages/cheroot/server.py", line 2030, in tick
    self.connections.expire()
  File "/usr/lib/python3.8/site-packages/cheroot/connections.py", line 107, in expire
    for sock_fd, conn in timed_out_connections:
  File "/usr/lib/python3.8/site-packages/cheroot/connections.py", line 102, in <genexpr>
    timed_out_connections = (
  File "/usr/lib/python3.8/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: dictionary changed size during iteration
```

**Comment by jcfp** [comment]
> I'm running SABnzbd on Arch Linux with the latest of everything, also getting the bug:
> `RuntimeError: dictionary changed size during iteration`

That's a different issue in cheroot, see #1572

**Comment by thezoggy** [comment]
horray, python 3.8.6 is out which has the bugfix
https://docs.python.org/release/3.8.6/whatsnew/changelog.html#python-3-8-6
 - https://bugs.python.org/issue31122

**Comment by pcm1ke** [comment]
I'm still having this same issue now.. 7/1/22 running latest sabnzbd from ppa on Ubuntu 22.04 LTS.

 [01/Jul/2022:21:47:17] ENGINE Error in HTTPServer.serve
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1810, in serve
    self._connections.run(self.expiration_interval)
  File "/usr/lib/python3/dist-packages/cheroot/connections.py", line 201, in run
    self._run(expiration_interval)
  File "/usr/lib/python3/dist-packages/cheroot/connections.py", line 218, in _run
    new_conn = self._from_server_socket(self.server.socket)
  File "/usr/lib/python3/dist-packages/cheroot/connections.py", line 272, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cheroot/ssl/builtin.py", line 277, in wrap
    s = self.context.wrap_socket(
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)

**Comment by thezoggy** [comment]
Lower level ssl error when connection is closed. Nothing sab can do to handle this (as it doesn't get bubbled up from webserver lib)

**Comment by Safihre** [comment]
Locking this, @thezoggy is right. Nothing we can do.
