### ISSUE TITLE
Download zip file detected as virus

### ISSUE THREAD

**Issue by stanleytng** [sabnzbd/sabnzbd#1606]
On my freshly installed Windows 10 Pro PC, I tried to download the latest Windows 10 (32-bits) installation file. Windows Security detected that the downloaded zipped file contains "Trojan:Win32/Ymacco.AA9A" (severe) virus and refused to download it. In this download page, https://sabnzbd.org/download-stats, the download for 3.0.2 Win32 (https://github.com/sabnzbd/sabnzbd/releases/download/3.0.2/SABnzbd-3.0.2-win32-bin.zip) and 3.0.1 Win32 (https://github.com/sabnzbd/sabnzbd/releases/download/3.0.1/SABnzbd-3.0.1-win32-bin.zip) are both flagged to contain virus.

However, the 3.0.0 win32 version (https://github.com/sabnzbd/sabnzbd/releases/download/3.0.0/SABnzbd-3.0.0-win32-bin.zip) is OK for the Microsoft virus detection. Also, the 3.0.2 Win-setup-exe (https://github.com/sabnzbd/sabnzbd/releases/download/3.0.2/SABnzbd-3.0.2-win-setup.exe) is OK. So , this problem seems to be only in the zipped files in versions 3.0.2 and 3.0.1.

**Comment by Safihre** [comment]
Yes it seems they just don't like our 32bit executables. Not much we can do.
I would suggest a 64bit OS!

**Comment by stanleytng** [comment]
Safihre, Thanks for your prompt response. Just want to confirm couple of things:
a) Please confirm that this is a false positive on Windows virus check and there is no actual virus.
b) Version 3.0.0 is OK with the virus checker. For users who are unable to upgrade to 64-bits Windows, would you recommend that they use this older version?

**Comment by Safihre** [comment]
Yes it's a false-positive. The content is the same as the 64bit package.
No, I don't recommend the older version due the bugs that were fixed in the 3.0.2 release compared to 3.0.0.

**Comment by stanleytng** [comment]
Safihre, Much appreciate your help. Closing this issue.

**Comment by Safihre** [comment]
Just out of curiosity, are you getting the same warnings with the 3.1.0Beta1 release that's on the website?

**Comment by stanleytng** [comment]
The 3.1.0Beta1 Windows Standalone (32bits) (https://github.com/sabnzbd/sabnzbd/releases/download/3.1.0Beta1/SABnzbd-3.1.0Beta1-win32-bin.zip) still fails the Microsoft virus check.  However, the equivalent 64-bits version zipped file is OK.

**Comment by thezoggy** [comment]
this is a pretty common thing out there in this day in age as many antivirus/malware type apps (event browsers) try and warn the user about possible issues if the file hasnt been downloaded that many times or if on quick scan the file contains .zip/.rar/.exe inside other files. some apps you can just whitelist, some apps allow you to submit apps for review so they can tweak. 

I used to get this type of thing on every sonarr/radarr update, I kept submitting them to symantec and eventually they 'fixed' their detection and it stopped.

for windows defender: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/antivirus-false-positives-negatives

**Comment by 88keyz** [comment]
I know this issue is closed but I was just wondering if you are using compressed executables as this can cause false negatives.

https://en.wikipedia.org/wiki/Executable_compression

> Also, some older virus scanners simply report all compressed executables as viruses because the decompressor stubs share some characteristics with those. Most modern virus scanners can unpack several different executable compression layers to check the actual executable inside, but some popular anti-virus and anti-malware scanners have had troubles with false positive alarms on compressed executables.

**Comment by jcfp** [comment]
Packing/executable compression is but one of many triggers. Sab triggers plenty of antivirus red flags: multiple executables inside, lots of network connections, a listening socket/web interface, scheduler, database stuff. AV makers may give their products fancy names loaded with buzzwords, "smart-this", "cloud-that", "AI" and so on but under all that varnish is still just a bunch of 'best guess' scoring mechanisms. Thus false positives remain until they add a manual override for the stuff they get enough complaints about, or enough time passes and their algorithms catch up.
